
server:
  port: 8080

spring:
  application:
    name: secondhand-market
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000ms

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhuxi.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.zhuxi: debug
bcrypt:
  strength: 10

jwt:
  admin-secret: 0Oruxa96a/sdrtYCgkzhsZz+oUVyVKMdLu+X9aPn0Nk=
  admin-expire: 86400
  admin-header: admin-token
  user-secret: MkU1pCpq+8tb/XQfHGC8HpQqd6gDsGYFqRzZ5YDDojQ=
  user-expire: 86400
  user-header: user-token
