server:
  port: 8080


spring:

# 数据源
  datasource:
    url: mysql://localhost:3306/second_hand_market
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# redis
#  data:
#   redis:
#     host: localhost
#     port: 6379
#     password: 123456
#     lettuce:
#      pool:
#        enabled: true # 启用连接池
#        max-active: 200
#        max-wait: 10000
#        max-idle: 10 # 最大空闲连接数
#        time-between-eviction-runs: 50 # 运行时间间隔
#     ssl:
#       enabled: false


# mq配置


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


