---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhuxi.
--- DateTime: 12/7/2025 10:00 AM
---

local lockKey = KEYS[1]
local threadId = ARGV[1]

local lockValue = redis.call("GET", lockKey)
if lockValue == threadId then
    redis.call("DEL", lockKey)
    return 1
else
    return 0
end